---
title: "Data Wrangling Function for `blackstone`"
output: html_document
date: "2024-05-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
    fig.width = 8,
    fig.height = 6)

# Load Libraries:
library(magrittr)
library(tidyverse)

######### Data
items <- dplyr::tibble(
  pre_Organization = c(1, 2, 3, 4, 5, 4, 3, 2, 1),
  post_Organization = dplyr::if_else(pre_Organization < 5, pre_Organization + 1, pre_Organization),
  pre_Source = c(2, 2, 3, 5, 4, 3, 2, 1, 2),
  post_Source = dplyr::if_else(pre_Source < 4, pre_Source + 2, pre_Source),
  pre_Publish = c(1, 1, 1, 2, 2, 2, 3, 3, 3),
  post_Publish = pre_Publish + 2,
  pre_Write = c(2, 2, 2, 3, 3, 3, 4, 4, 4),
  post_Write = pre_Write + 1,
  pre_Research = c(1, 1, 2, 2, 3, 3, 4, 4, 4),
  post_Research = pre_Research + 1
)

items_single <- dplyr::tibble(
  Organization = c(1, 2, 3, 4, 5, 4, 3, 2, 1),
  Source = c(2, 2, 3, 5, 4, 3, 2, 1, 2),
  Publish = c(1, 1, 1, 2, 2, 2, 3, 3, 3),
  Write = c(2, 2, 2, 3, 3, 3, 4, 4, 4),
  Research = c(1, 1, 2, 2, 3, 3, 4, 4, 4),
)

# Set scale_labels for recodeCat function:
# scale_labels as a named character vector, items in correct order:
levels_min_ext_named <- c(
  "Minimal" = "1", "Slight" = "2", "Moderate" = "3",
  "Good" = "4", "Extensive" = "5"
)

# bar_scale_labels as just the names from levels_min_ext:
bar_scale_labels <- names(levels_min_ext_named)

levels_min_ext <- names(levels_min_ext_named) 
# Question labels as a named vector with the naming structure
# like this: c("new label" = "original variable name"):
question_labels <- c(
  "Publish a lot of high quality papers" = "Publish",
  "Write a lot of research papers" = "Write",
  "Research in a lab with faculty" = "Research",
  "Organization of a large research project" = "Organization",
  "Source work for a research paper" = "Source"
)

# Recode the numeric to factor variables using the levels from levels_min_ext:
cat_items <- blackstone::recodeCat(items, levels_min_ext_named)
cat_items_single <- blackstone::recodeCat(items_single, levels_min_ext_named)

# Select the factor variables:
items_pre_post <- cat_items %>% dplyr::select(dplyr::where(is.factor)) %>% select(contains(c("pre_", "post_")))
# %>% rename_with(~ paste0("pre_",stringr::str_replace(.,"_pre","")), .cols = contains("pre")) 
items_single <- cat_items_single %>% dplyr::select(dplyr::where(is.factor)) %>% select(!contains(c("pre_", "post_")))
```



```{r}
# ARGS:
new_df <- items_pre_post
scale_labels <- levels_min_ext
na_remove <- TRUE # if true remove NA, if FALSE convert to character and make the lowest factor:

# For pre-post data:
# Test if all vars contain c("pre_", "post_"), if not then stop and return an error message:
test_names <- new_df %>% names() %>% str_detect(., paste(c("pre_", "post_"), collapse = "|"))
if (any(test_names == FALSE)) {
    stop("the variables do not have `pre_` and/or `post_` prefixes, makes sure all variables have the correct prefixes.")
}
# new_df %>% select(contains(c("pre_", "post_"))) %>% names() 
# test_names <- new_df %>% names() %>% str_detect(., paste(c("pre_", "post_"), collapse = "|"))
# any(test_names == FALSE)
# test_names <- append(test_names, FALSE) 
# all(test_names == TRUE)


# Sets up new_df:
    new_df <- new_df %>%
      tidyr::pivot_longer(contains(c("pre_", "post_")), names_to = "question", values_to = "response") %>%
      dplyr::mutate(question = stringr::str_remove(.data$question, "cat_")) %>%
      tidyr::separate(.data$question, into = c("timing", "question"), sep = "_", extra = "merge") %>%
      dplyr::mutate(response = factor(.data$response, levels = scale_labels)) %>%
      dplyr::group_by(.data$question, .data$timing, .data$response) %>%
      dplyr::summarize(n_answers = dplyr::n(), .groups = "keep") %>%
      dplyr::ungroup() %>%
      tidyr::drop_na() %>% 
      dplyr::group_by(.data$question, .data$timing) %>%
      dplyr::mutate(
        percent_answers = .data$n_answers / sum(.data$n_answers),
        timing = stringr::str_to_title(.data$timing), # capitalize timing
        timing = factor(.data$timing, levels = c("Pre", "Post"))
      ) %>%
      dplyr::ungroup()
    
    new_df
```

```{r}
# new_df <- items_pre_post 
# # with NA row:          
# new_df <- rows_append(new_df, as_tibble_row(setNames(rep(NA, NCOL(new_df)), names(new_df))))
# scale_labels <- levels_min_ext
# pre_post <- TRUE
# na_remove <- TRUE # if true remove NA, if FALSE convert to character and make the lowest factor:

# Start writing new function, name it dataVizCleaning() or something better, 4 args: df, pre_post, scale_labels, na_remove,:
dataVizCleaning <- function(df, scale_labels, pre_post = TRUE, na_remove = TRUE) {
    
    if (isTRUE(na_remove)) { # NA's are dropped in this first section:
        # Start of data manipulation: ----
        # Make sure the all vars in df are factors with scale_labels as their levels:
        new_df <- {{ df }} %>% dplyr::mutate(dplyr::across(tidyselect::everything(), ~ factor(., levels = scale_labels)))
        
        if (isTRUE(pre_post)) { # Processes the data with "pre_" and "post_" prefixes, adds a `timing` var:
            # For pre-post data:
            # Test if all vars contain c("pre_", "post_"), if not then stop and return an error message:
            test_names <- {{ df }} %>% names() %>% str_detect(., paste(c("pre_", "post_"), collapse = "|"))
            if (any(test_names == FALSE)) {
                stop("the variables do not have `pre_` and/or `post_` prefixes, makes sure all variables have the correct prefixes.")
            }
    
            # Sets up new_df:
            new_df <- new_df %>%
                tidyr::pivot_longer(contains(c("pre_", "post_")), names_to = "question", values_to = "response") %>%
                dplyr::mutate(question = stringr::str_remove(.data$question, "cat_")) %>%
                tidyr::separate(.data$question, into = c("timing", "question"), sep = "_", extra = "merge") %>%
                dplyr::mutate(response = factor(.data$response, levels = scale_labels)) %>%
                dplyr::group_by(.data$question, .data$timing, .data$response) %>%
                dplyr::summarize(n_answers = dplyr::n(), .groups = "keep") %>%
                dplyr::ungroup() %>%
                tidyr::drop_na() %>% # drops NA's
                dplyr::group_by(.data$question, .data$timing) %>%
                dplyr::mutate(
                    percent_answers = .data$n_answers / sum(.data$n_answers),
                    percent_answers_label = scales::percent(.data$percent_answers, accuracy = 1),
                    timing = stringr::str_to_title(.data$timing), # capitalize timing
                    timing = factor(.data$timing, levels = c("Pre", "Post")),
                    response = factor(.data$response, levels = scale_labels)
                ) %>%
                dplyr::ungroup() %>%
                dplyr::arrange(.data$question, .data$timing, .data$response)
        # end of if pre_post == TRUE
        } else if (isFALSE(pre_post)) {
            # If pre_post is FALSE, set up new_df:
            new_df <- new_df %>%
                tidyr::pivot_longer(tidyselect::everything(), names_to = "question", values_to = "response") %>%
                dplyr::mutate(question = stringr::str_remove(.data$question, "cat_"),
                              response = factor(.data$response, levels = scale_labels)) %>%
                dplyr::group_by(.data$question, .data$response) %>%
                dplyr::summarize(n_answers = dplyr::n(), .groups = "keep") %>%
                dplyr::ungroup() %>%
                tidyr::drop_na() %>% # drops NA's
                dplyr::group_by(.data$question) %>%
                dplyr::mutate(
                    percent_answers = .data$n_answers / sum(.data$n_answers),
                    percent_answers_label = scales::percent(.data$percent_answers, accuracy = 1)
                ) %>%
                dplyr::ungroup()%>%
                dplyr::arrange(.data$question, .data$response)
        } # end of if pre_post == FALSE
    # end of if na_remove == TRUE 
    } else if (isFALSE(na_remove)) { # Code section to keep NA's: recode as `Missing` and count as the lowest factor:
        # Add missing as the lowest level of `scale_labels`:
        scale_labels <- append(scale_labels, "Missing", after = 0)
        # # Start of data manipulation: ----
        # changes NA to "Missing" and then all vars in df are factors with scale_labels as their levels:
        new_df <- {{ df }} %>% dplyr::mutate(dplyr::across(tidyr::everything(), ~ case_when(is.na(.) ~ "Missing", TRUE ~ .)),
                                             dplyr::across(tidyselect::everything(), ~ factor(., levels = scale_labels)))
            
        if (isTRUE(pre_post)) { # Processes the data with "pre_" and "post_" prefixes, adds a `timing` var:
            # For pre-post data:
            # Test if all vars contain c("pre_", "post_"), if not then stop and return an error message:
            test_names <- {{ df }} %>% names() %>% str_detect(., paste(c("pre_", "post_"), collapse = "|"))
            if (any(test_names == FALSE)) {
                stop("the variables do not have `pre_` and/or `post_` prefixes, makes sure all variables have the correct prefixes.")
            }
            # Process `new_df` for pre_post == TRUE
            new_df <- new_df %>% 
                tidyr::pivot_longer(contains(c("pre_", "post_")), names_to = "question", values_to = "response") %>%
                dplyr::mutate(question = stringr::str_remove(.data$question, "cat_")) %>%
                tidyr::separate(.data$question, into = c("timing", "question"), sep = "_", extra = "merge") %>%
                dplyr::mutate(response = factor(.data$response, levels = scale_labels)) %>%
                dplyr::group_by(.data$question, .data$timing, .data$response) %>%
                dplyr::summarize(n_answers = dplyr::n(), .groups = "keep") %>%
                dplyr::ungroup() %>%
                dplyr::group_by(.data$question, .data$timing) %>%
                dplyr::mutate(
                    percent_answers = .data$n_answers / sum(.data$n_answers),
                    percent_answers_label = scales::percent(.data$percent_answers, accuracy = 1),
                    timing = stringr::str_to_title(.data$timing), # capitalize timing
                    timing = factor(.data$timing, levels = c("Pre", "Post"))
                ) %>%
                dplyr::ungroup()%>%
                dplyr::arrange(.data$question, .data$timing, .data$response)
        # end of if pre_post == TRUE
        } else if (isFALSE(pre_post)) {
            # If pre_post is FALSE, set up new_df, which already has NA's recoded to missing from above:
            new_df <- new_df  %>%
                tidyr::pivot_longer(tidyselect::everything(), names_to = "question", values_to = "response") %>%
                dplyr::mutate(question = stringr::str_remove(.data$question, "cat_"),
                              response = factor(.data$response, levels = scale_labels)) %>%
                dplyr::group_by(.data$question, .data$response) %>%
                dplyr::summarize(n_answers = dplyr::n(), .groups = "keep") %>%
                dplyr::ungroup() %>%
                dplyr::group_by(.data$question) %>%
                dplyr::mutate(
                  percent_answers = .data$n_answers / sum(.data$n_answers),
                  percent_answers_label = scales::percent(.data$percent_answers, accuracy = 1)
                ) %>%
                dplyr::ungroup() %>%
                dplyr::arrange(.data$question, .data$response)
        } # end of if pre_post == FALSE
    } # end of if na_remove == FALSE
            
    return(new_df) 
} # end of function dataVizCleaning()


```

```{r}

items_pre_post_na <- rows_append(items_pre_post, as_tibble_row(setNames(rep(NA, NCOL(items_pre_post)), names(items_pre_post))))
items_single_na <- rows_append(items_single, as_tibble_row(setNames(rep(NA, NCOL(items_single)), names(items_single))))
# items_single 
# items_pre_post
# Test all args:
dataVizCleaning(df = items_pre_post_na, pre_post = TRUE, scale_labels = levels_min_ext, na_remove = TRUE)
dataVizCleaning(df = items_pre_post_na, pre_post = TRUE, scale_labels = levels_min_ext, na_remove = FALSE)
dataVizCleaning(df = items_pre_post_na, pre_post = FALSE, scale_labels = levels_min_ext, na_remove = TRUE) 
dataVizCleaning(df = items_pre_post_na, pre_post = FALSE, scale_labels = levels_min_ext, na_remove = FALSE) 
# fct_unique(single_df[["response"]])


```

```{r}
# items_pre_post %>% blackstone::dataSumm() %>% filter(stringr::str_detect(question, "pre_")) %>% arrange(question)
# items_pre_post %>% blackstone::dataSumm() %>% filter(stringr::str_detect(question, "post_")) %>% arrange(question)
items_single %>% blackstone::dataSumm() %>% arrange(question)

```


```{r data for example}
# Add roxygen tags and then add to examples portion of new `R` script.

# Fake data for examples, first are single items and the second has pre-post data with correct prefixes in variable names:
items_single <- tibble::tibble(
    Organization = c("Minimal", "Slight", "Moderate", "Good", "Extensive", "Good", "Moderate", "Slight", "Minimal"),
    Source = c("Slight", "Slight", "Moderate", "Extensive", "Good", "Moderate", "Slight", "Minimal", "Slight"),
    Publish = c("Minimal", "Minimal", "Minimal", "Slight", "Slight", "Slight", "Moderate", "Moderate", "Moderate"),
    Write = c("Slight", "Slight", "Slight", "Moderate", "Moderate", "Moderate", "Good", "Good", "Good"),
    Research = c("Minimal", "Minimal", "Slight", "Slight", "Moderate", "Moderate", "Good", "Good", "Good")
)

items_pre_post <- tibble::tibble(
   pre_Organization = c("Minimal", "Slight", "Moderate", "Good", "Extensive", "Good", "Moderate", "Slight", "Minimal"),
   post_Organization = c("Slight", "Moderate", "Good", "Extensive", "Extensive", "Extensive", "Good", "Moderate", "Slight"),
   pre_Source = c("Slight", "Slight", "Moderate", "Extensive", "Good", "Moderate", "Slight", "Minimal", "Slight"),
   post_Source = c("Good", "Good", "Extensive", "Extensive", "Good", "Extensive", "Good", "Moderate", "Good"),
   pre_Publish = c("Minimal", "Minimal", "Minimal", "Slight", "Slight", "Slight", "Moderate", "Moderate", "Moderate"),
   post_Publish = c("Moderate", "Moderate", "Moderate", "Good", "Good", "Good", "Extensive", "Extensive", "Extensive"),
   pre_Write = c("Slight", "Slight", "Slight", "Moderate", "Moderate", "Moderate", "Good", "Good", "Good"),
   post_Write = c("Moderate", "Moderate", "Moderate", "Good", "Good", "Good", "Extensive", "Extensive", "Extensive"),
   pre_Research = c("Minimal", "Minimal", "Slight", "Slight", "Moderate", "Moderate", "Good", "Good", "Good"),
   post_Research = c("Slight", "Slight", "Moderate", "Moderate", "Good", "Good", "Extensive", "Extensive", "Extensive")
)
# Add a row of NA values to each fake data set:
items_pre_post_na <- rows_append(items_pre_post, as_tibble_row(setNames(rep(NA, NCOL(items_pre_post)), names(items_pre_post))))
items_single_na <- rows_append(items_single, as_tibble_row(setNames(rep(NA, NCOL(items_single)), names(items_single))))

# Likert scale to pass to `scale_labels` that is the order to arrange each variable:
levels_min_ext <- c("Minimal", "Slight", "Moderate", "Good", "Extensive")

dataVizCleaning(df = items_single, pre_post = FALSE, scale_labels = levels_min_ext, na_remove = TRUE) 
dataVizCleaning(df = items_single_na, pre_post = FALSE, scale_labels = levels_min_ext, na_remove = FALSE) 
dataVizCleaning(df = items_pre_post, pre_post = TRUE, scale_labels = levels_min_ext, na_remove = TRUE)
dataVizCleaning(df = items_pre_post_na, pre_post = TRUE, scale_labels = levels_min_ext, na_remove = FALSE)

```




