---
title: "Fix Totals for Labels"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk[["set"]](echo = FALSE, 
    fig.width = 8,
    fig.height = 6)

# Load Libraries:
library(magrittr)
library(dplyr)
library(blackstone) # blackstone R package

set.seed(424429) # for reproducibility


######## Data
items <- dplyr::tibble(
  pre_Organization = c(1, 2, 3, 4, 5, 4, 3, 2, 1),
  post_Organization = dplyr::if_else(pre_Organization < 5, pre_Organization + 1, pre_Organization),
  pre_Source = c(2, 2, 3, 5, 4, 3, 2, 1, 2),
  post_Source = dplyr::if_else(pre_Source < 4, pre_Source + 2, pre_Source),
  pre_Publish = c(1, 1, 1, 2, 2, 2, 3, 3, 3),
  post_Publish = pre_Publish + 2,
  pre_Write = c(2, 2, 2, 3, 3, 3, 4, 4, 4),
  post_Write = pre_Write + 1,
  pre_Research = c(1, 1, 2, 2, 3, 3, 4, 4, 4),
  post_Research = pre_Research + 1
)


items_single <- dplyr::tibble(
  Organization = c(1, 2, 3, 4, 5, 4, 3, 2, 1),
  Source = c(2, 2, 3, 5, 4, 3, 2, 1, 2),
  Publish = c(1, 1, 1, 2, 2, 2, 3, 3, 3),
  Write = c(2, 2, 2, 3, 3, 3, 4, 4, 4),
  Research = c(1, 1, 2, 2, 3, 3, 4, 4, 4),
)

# Create tibbles of random missing values:
items_na <- items %>% mutate(across(everything(), ~ replace(., sample(row_number(), size = 1, replace = F), NA) ))
items_single_na <- items_single %>% mutate(across(everything(), ~ replace(., sample(row_number(), size = 1, replace = F), NA) ))

# Set scale_labels for recodeCat function:
# scale_labels as a named character vector, items in correct order:
levels_min_ext_named <- c(
  "Minimal" = "1", "Slight" = "2", "Moderate" = "3",
  "Good" = "4", "Extensive" = "5"
)

# levels_min_ext as just the names from levels_min_ext_named:
levels_min_ext <- names(levels_min_ext_named) 

# Question labels as a named vector with the naming structure
# like this: c("new label" = "original variable name"):
question_labels <- c(
  "Publish a lot of high quality papers" = "Publish",
  "Write a lot of research papers" = "Write",
  "Research in a lab with faculty" = "Research",
  "Organization of a large research project" = "Organization",
  "Source work for a research paper" = "Source"
)

# Recode the numeric to factor variables using the levels from levels_min_ext and Select the factor variables:
cat_items <- blackstone::recodeCat(items, levels_min_ext_named) %>% dplyr::select(dplyr::where(is.factor))
cat_items_single <- blackstone::recodeCat(items_single, levels_min_ext_named) %>% dplyr::select(dplyr::where(is.factor))

# Recode the numeric to factor variables using the levels from levels_min_ext and Select the factor variables:
cat_items_na <- blackstone::recodeCat(items_na, levels_min_ext_named) %>% dplyr::select(dplyr::where(is.factor))
cat_items_single_na <- blackstone::recodeCat(items_single, levels_min_ext_named) %>% dplyr::select(dplyr::where(is.factor))


# for grouped arrow chart:
# add a grouping var to the data set `items`:
items_group <- dplyr::tibble(
   items_na,
   edu_level = factor(c(
       "grad", "undergrad", "grad", "undergrad", "grad",
       "undergrad", "undergrad", "grad", "undergrad"
  ), levels = c("grad", "undergrad"))
 ) %>% mutate(
            post_Research = dplyr::if_else(pre_Research > 2, pre_Research - 2, pre_Research)
 )
```


```{r}
df <- cat_items_na
scale_labels <- levels_min_ext

# dataVizCleaning <- function(df, scale_labels, pre_post = FALSE, na_remove = TRUE) {
#     . <- NULL # Set . to NULL to stop message when using dot notation in mutate:
# 
#     if (isTRUE(na_remove)) { # NA's are dropped in this first section:
        # Start of data manipulation: ----
        # Make sure the all vars in df are factors with scale_labels as their levels:
        new_df <- {{ df }} %>% dplyr::mutate(dplyr::across(tidyselect::everything(), ~ factor(., levels = scale_labels)))

            # For pre-post data:
            # Test if all vars contain c("pre_", "post_"), if not then stop and return an error message:
            test_names <- {{ df }} %>% names() %>% stringr::str_to_lower() %>%
                stringr::str_detect(., paste(c("pre_", "post_"), collapse = "|"))
            if (any(test_names == FALSE)) {
                stop("the variables do not have `pre_` and/or `post_` prefixes, makes sure all variables have the correct prefixes.")
            }

            # Sets up new_df:
            new_df <- new_df %>%
                tidyr::pivot_longer(tidyselect::contains(c("pre_", "post_")), names_to = "question", values_to = "response") %>%
                dplyr::mutate(question = stringr::str_remove(.data$question, "cat_")) %>%
                tidyr::separate(.data$question, into = c("timing", "question"), sep = "_", extra = "merge") %>%
                dplyr::mutate(response = factor(.data$response, levels = scale_labels)) %>%
                dplyr::group_by(.data$question, .data$timing, .data$response) %>%
                dplyr::summarize(n_answers = dplyr::n(), .groups = "keep") %>%
                dplyr::ungroup() %>%
                tidyr::drop_na() %>% # drops NA's
                dplyr::group_by(.data$question, .data$timing) %>%
                dplyr::mutate(
                    percent_answers = .data$n_answers / sum(.data$n_answers),
                    percent_answers_label = scales::percent(.data$percent_answers, accuracy = 1),
                    timing = stringr::str_to_title(.data$timing), # capitalize timing
                    timing = factor(.data$timing, levels = c("Pre", "Post"))
                ) %>%
                dplyr::ungroup() %>%
                dplyr::arrange(.data$question, .data$timing, .data$response)
            # end of if pre_post == TRUE
        totals_new_df <- {{ df }} %>%
            tidyr::pivot_longer(tidyselect::contains(c("pre_", "post_")), names_to = "question", values_to = "response") %>%
            dplyr::mutate(question = stringr::str_remove(.data$question, "cat_")) %>%
            tidyr::separate(.data$question, into = c("timing", "question"), sep = "_", extra = "merge") %>%
            dplyr::group_by(.data[["question"]], .data[["timing"]]) %>%
            dplyr::mutate(timing = stringr::str_to_title(.data$timing), # capitalize timing
                          timing = factor(.data$timing, levels = c("Pre", "Post"))
            ) %>% 
            tidyr::drop_na() %>% # drops NA's
            dplyr::summarize(total = dplyr::n(), .groups = "keep") %>%
            dplyr::ungroup()
        # Join the `total` column to arrow_df
        new_df <- new_df %>% dplyr::full_join(totals_new_df,by = dplyr::join_by("question", "timing"))
```


```{r}
blackstone::arrowChart(df = items_na, scale_labels = levels_min_ext, 
                       overall_n = F, question_labels = question_labels, question_order = TRUE)
```

```{r}
blackstone::arrowChartGroup(df = items_group, group = "edu_level", group_levels = c("grad", "undergrad"), scale_labels = levels_min_ext, 
                           overall_n = F, question_labels = NULL, question_order = FALSE)
```

