---
title: "`groupedTable()` Function Development"
author: "Zack Crowley"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk[["set"]](
    collapse = TRUE,
    warning = FALSE, 
    message = FALSE, 
    fig.width = 7,
    fig.height = 6,
    out.width = "100%"
    )
# Prevents sci notation and sets the output of decimals to 4 (0.0000):
options(scipen = 999, digits = 4,
        tibble.print_min = 5, tibble.print_max = 5)
# Set seed to reproduce data:
set.seed(424629)

# # Install packages: (if first time running this)
# # install.packages("pak")
# pak::pak("zwcrowley/blackstone")
# 
# # install.packages("extrafont")
# library(extrafont)
# # Import fonts to get "Arial", this only has to be done one time, then
# # `blackstone` package will use the code below to load the fonts automatically
# # for the functions that require that step:
# extrafont::font_import()
# # Load all fonts:
# extrafont::loadfonts("all", quiet = TRUE)

# Load Libraries:
# library(readr) # Importing data
# library(rstatix) # pipe-friendly statistical tests
# library(ggpubr) # ggplot for statistical analysis
# library(tidyselect) # tidyverse data selection
# library(tidyr) # tidyverse tidy data manipulation
# library(tibble) # tidyverse tables
# library(purrr) # tidyverse functional programming
# library(dplyr) # tidyverse Data manipulation
# library(blackstone) # `blackstone` R package

# Demographic levels:
gender_levels <- c("Female","Male","Non-binary", "Do not wish to specify")
role_levels <- c("Undergraduate student", "Graduate student", "Postdoc",  "Faculty")
ethnicity_levels <- c("White (Non-Hispanic/Latino)", "Asian", "Black",  "Hispanic or Latino", "American Indian or Alaskan Native",
                      "Native Hawaiian or other Pacific Islander", "Do not wish to specify")
first_gen_levels <- c("Yes", "No", "I'm not sure")

### read in data:
sm_data_demos <- readr::read_csv(blackstone::blackstoneExample("sm_data_demo.csv"), show_col_types = FALSE) %>% 
                    dplyr::mutate(gender = factor(gender, levels = gender_levels),
                                  role = factor(role, levels = role_levels),
                                  ethnicity = factor(ethnicity, levels = ethnicity_levels),
                                  first_gen = factor(first_gen, levels = first_gen_levels),
                                  )
sm_data_demos
```

Fixing a bug in `groupedTable()` where the wrong names were being created when grouped/split by a variable:

Here is a function that will italicize `n` in all of the names for the columns:

- this needs to be added to the helper functions in `blackstone`

```{r include=FALSE}
# TODO: delete this after figuring out bug in groupdTable(): and setting function below up in `blackstone` package `italicize_n_header`

# library(flextable)
# library(dplyr)
# library(purrr)
# library(stringr)

# Example data frame
df_short <- data.frame(value1 = 1:5, value2 = 6:10)

# Renaming columns dynamically to include "(n = X)"
total_n <- 10
df_short <- df_short %>%
  dplyr::rename(!!paste0("Header for (n = ", total_n, ") Value 1") := value1,
                !!paste0("Another Header \n(n = ", total_n, ") Value 2") := value2)

# Create the initial flextable
ft <- flextable::flextable(df_short)

# Extract column names
col_names <- names(df_short)

stringr::str_split(col_names[1], "(?<=\\()n =|n =", n = 2, simplify = TRUE)

# Function to apply italics to 'n' dynamically using regular expressions
italicize_n_header <- function(header_name) {
  # Match both "(n =" and "n =" or "\n(n"
  if (stringr::str_detect(header_name, "\\(?n =|\\n\\(n")) {
    # Split the string into parts: before and after 'n ='
    parts <- stringr::str_split(header_name, "(?<=\\()n =|n =", n = 2, simplify = TRUE)
    
    # Get prefix and suffix
    prefix <- parts[1]  # Text before "n ="
    suffix <- parts[2]  # Text after "n ="
    
    # Replace \n with a newline in the prefix
    prefix <- stringr::str_replace(prefix, "\\n", "\n")
    
    # Create the as_paragraph expression for the header
    flextable::as_paragraph(prefix, flextable::as_i("n"), " = ", suffix)
  } else {
    # If no "n" pattern is found, return the name as a paragraph
    flextable::as_paragraph(header_name)
  }
}

# Use purrr::walk2() to apply italic formatting to each header dynamically
purrr::walk2(seq_along(col_names), col_names, function(i, header_text) {
  ft <<- flextable::compose(ft, j = i, part = "header", value = italicize_n_header(header_text))
})

# View the flextable with formatted headers
ft
```

```{r include=FALSE}
fellowship_data %>% select(role, contains("grad_interest_") & where(is.factor)) %>% 
            mutate(role = forcats::fct_infreq(role)) %>% 
            blackstone::groupedTable(., col_group = "role")
# For testing group part of function:
df = fellowship_data %>% select(role, contains("grad_interest_") & where(is.factor)) %>% 
            mutate(role = forcats::fct_infreq(role)) #role = factor(role, levels = levels_role))

col_group = "role"
str_width = 20
# For testing NO group part of function:
col_group = NULL
str_width = 20
df = fellowship_data %>% select(contains("grad_interest_") & where(is.factor)) 

####
df_total <- {{ df }} %>% dplyr::select(-c(!!sym(col_group)))

        total_n <- {{ df }} %>% dplyr::summarise(totals = dplyr::n())
        # Create a table of all vars without grouping, table_total
        # Select all cols except groups:
        cols <- {{ df }}  %>% dplyr::select(-c(!!sym(col_group))) %>% names()
        
        purrr::map(cols, \(x) df_total %>% dplyr::count(.data[[x]]) %>% dplyr::arrange(.data[[x]]) %>% 
                       dplyr::mutate(question = colnames(df_total[x][1]), # set new var as the name of the original current data
                                     response = .data[[x]], # copy original col var as response
                                     percent_answers = .data[["n"]] / sum(.data[["n"]])) %>% 
                       dplyr::relocate("question":"response", .after = .data[[x]])
                   )
```


## Create new function for `groupedTable()`:

```{r include=FALSE}
# TODO: add as a helper function to `blackstone` package:
# Function to apply italics to 'n' dynamically using regular expressions
italicize_n_header <- function(header_name) {
  # Match both "(n =" and "n =" or "\n(n"
  if (stringr::str_detect(header_name, "\\(?n =|\\n\\(n")) {
    # Split the string into parts: before and after 'n ='
    parts <- stringr::str_split(header_name, "(?<=\\()n =|n =", n = 2, simplify = TRUE)
    
    # Get prefix and suffix
    prefix <- parts[1]  # Text before "n ="
    suffix <- parts[2]  # Text after "n ="
    
    # Replace \n with a newline in the prefix
    prefix <- stringr::str_replace(prefix, "\\n", "\n")
    
    # Create the as_paragraph expression for the header
    flextable::as_paragraph(prefix, flextable::as_i("n"), " = ", suffix)
  } else {
    # If no "n" pattern is found, return the name as a paragraph
    flextable::as_paragraph(header_name)
  }
}

# TODO: fix blackstone::groupedTable() by changing the data call to this:
if (is.null(col_group)) { # Overall table section
    # Get total_n for overall/total df:
    total_n <- {{ df }} %>% dplyr::summarize(total_n = dplyr::n()) %>% tibble::deframe()
    # Format data to get long-form counts and percentages in one column for total/overall table: 
    table <- {{ df }} %>% 
                tidyr::pivot_longer(dplyr::everything(), names_to = "question", values_to = "response") %>%
                dplyr::mutate(question = forcats::fct_inorder(.data[["question"]])) %>% 
                dplyr::group_by(.data[["question"]], .data[["response"]]) %>%
                dplyr::summarize(n_answers = dplyr::n(), .groups = "keep") %>%
                dplyr::ungroup() %>%
                dplyr::group_by(.data[["question"]]) %>%
                dplyr::mutate(
                   percent_answers = .data[["n_answers"]] / sum(.data[["n_answers"]]),
                   percent_answers_label = paste0("(",scales::percent(.data[["percent_answers"]], accuracy = 1),")"),
                   percent_answers_label = dplyr::if_else(.data[["percent_answers_label"]] == "(0%)", "(<1%)", .data[["percent_answers_label"]])
                ) %>%
                dplyr::ungroup() %>%
                dplyr::arrange(.data[["question"]], .data[["response"]]) %>% 
                tidyr::unite("value", c(n_answers,percent_answers_label), sep = " ") %>% 
                dplyr::rename_with(~ glue::glue("n = {total_n}"), value) %>% 
                dplyr::select(-c("percent_answers")) %>% 
                dplyr::mutate(dplyr::across(-c("question","response"), ~ dplyr::case_when(is.na(.) ~ "-", TRUE ~ .)),
                        response = if (anyNA(.data[["response"]])) { # if NA's exist, convert NA's in `response` to "Missing" and add as the last factor level
                                            factor(dplyr::coalesce(as.character(.data[["response"]]), "Missing"), 
                                                   levels = c(levels(.data[["response"]]), "Missing")) 
                                        } else { .data[["response"]] }
                        ) 

} else if (!is.null(col_group)) { # if col_group is supplied and not NULL: Grouped Table section
    # Calculate columns for `col_group` by using `tidyr::nest()`:!!sym(col_group) or .data[[col_group]]
    table <- {{ df }} %>% dplyr::group_by(.data[[col_group]]) %>% tidyr::nest() %>% 
                        dplyr::bind_rows(tibble::tibble({{col_group}} := factor("Total"),
                                         data = list({{ df }} %>% dplyr::select(-{{col_group}})))) %>%
                        dplyr::mutate({{col_group}} := forcats::fct_relevel(.data[[col_group]], "Total", after = Inf)) %>% 
                        dplyr::arrange(.data[[col_group]]) %>% 
                        dplyr::mutate(var_counts = purrr::map(data, function(df) df %>%
                                        tidyr::pivot_longer(tidyselect::everything(), names_to = "question", values_to = "response") %>%
                                        dplyr::mutate(question = forcats::fct_inorder(.data[["question"]])) %>% 
                                        dplyr::group_by(.data[["question"]], .data[["response"]]) %>%
                                        dplyr::summarize(n_answers = dplyr::n(), .groups = "keep") %>%
                                        dplyr::ungroup() %>%
                                        dplyr::group_by(.data[["question"]]) %>%
                                        dplyr::mutate(
                                            percent_answers = .data[["n_answers"]] / sum(.data[["n_answers"]]),
                                            percent_answers_label = paste0("(",scales::percent(.data[["percent_answers"]], accuracy = 1),")"),
                                            percent_answers_label = dplyr::if_else(.data[["percent_answers_label"]] == "(0%)", 
                                                                                   "(<1%)",.data[["percent_answers_label"]])
                                         ) %>%
                                         dplyr::ungroup() %>%
                                         dplyr::arrange(.data[["question"]], .data[["response"]]) %>% 
                                         tidyr::unite("value", c(n_answers,percent_answers_label), sep = " ") %>% 
                                         dplyr::select(-c("percent_answers"))
                                        ),
                               total_n = purrr::map(data, function(df) df %>% dplyr::summarise(totals = dplyr::n()))
                               ) %>% 
                tidyr::unnest(c(var_counts, total_n)) %>% dplyr::arrange({{col_group}}) %>% dplyr::select(-data) %>% dplyr::ungroup() %>%
                # paste0(!!sym(col_group),"\n (n = ", totals,")") if glue below does not work:
                dplyr::mutate({{col_group}} := forcats::fct_inorder(glue::glue("{.data[[col_group]]}\n (n = {totals})")) 
                ) %>% dplyr::select(-totals) %>% 
                tidyr::pivot_wider(names_from = {{col_group}}, values_from = "value") %>%
                dplyr::mutate(dplyr::across(-c("question","response"), ~ dplyr::case_when(is.na(.) ~ "-", TRUE ~ .))) %>% 
                dplyr::arrange(.data[["question"]], .data[["response"]]) %>% 
                dplyr::mutate(response = if (anyNA(.data[["response"]])) {
                    factor(dplyr::coalesce(as.character(.data[["response"]]), "Missing"), levels = c(levels(.data[["response"]]), "Missing")) } else {
                    .data[["response"]] # if any NA's exist then: Convert all NA's in `response` to "Missing" and add "Missing" as the last factor level
                    })
} # end of if/else is.null(col_group)

# Extract column names before turning into flextable:
# col_names <- names(table)

# Convert to flextable and format for final table:
table <- table %>% dplyr::mutate(question = stringr::str_wrap(.data[["question"]], width = str_width)) %>% 
            flextable::as_grouped_data(., "question") %>%
            flextable::flextable() %>% 
            flextable::mk_par(j = 3:flextable::ncol_keys(.),
                              part = "header",
                        value = italicize_n_header(.), 
                        use_dot = TRUE) %>% 
            flextable::align(j = flextable::ncol_keys(.), align = "center", part = "all") %>% # center last column
            flextable::colformat_double(digits = 2) %>% 
# Use purrr::walk2() to apply italic formatting to each header dynamically using helper function italicize_n_header():
# walk2(seq_along(col_names), col_names, function(i, header_text) {
#   table <<- flextable::compose(table, j = i, part = "header", value = italicize_n_header(header_text))
# })
# Format the rest of the table using flextable functions:  table <- table %>%  
            flextable::set_header_labels(question = "Question", response = "Response") %>%
            flextable::fontsize(size = 11, part = "header") %>%
            flextable::fontsize(size = 10, part = "body") %>%
            flextable::hline(part = "all", border = officer::fp_border(color = "gray")) %>%
            flextable::bg(bg = blackstoneColors["dark_blue"], part = "header") %>%
            flextable::color(color = "white", part = "header") %>%
            flextable::bg(i = ~ !is.na(question), bg = blackstoneColors["light_grey"], part = "body") %>%
            flextable::footnote(i = 2, j = flextable::ncol_keys(.), value = flextable::as_paragraph(flextable::as_i(c("n")), c(" (%)")),
                                ref_symbols = c("1"), part = "body") %>%  # add footnote referencing last header col
            flextable::autofit(part = "all")

table

```



