---
title: "SurveyMonkey Data Test"
author: "ZC"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk[["set"]](
    echo = FALSE, 
    fig.width = 8,
    fig.height = 6
    )

# Prevents sci notation and sets the output of decimals to 4 (0.0000):
options(scipen = 999, digits = 4)

# Set seed to reproduce data:
set.seed(04240629)

# Load Libraries:
library(readr)
library(dplyr)
library(bre) # blackstone R package
```


```{r}
# Helper function to get headers to long form tibble:
getHeaders <- function(file_path) {
    ext <- tools::file_ext(file_path) # get file_path extension
    # Get the headers from either .csv or .xlsx by reading in just the first two rows when col_names is set to false:
    sm_data_headers <- switch(ext,
                              csv = readr::read_csv(file_path, col_names = FALSE, n_max = 2, show_col_types = FALSE), # only first two rows
                              xlsx = readxl::read_xlsx(file_path, col_names = FALSE, n_max = 2, .name_repair = "unique_quiet"), # only first two rows
                              # Return an error message if file is not .csx or .xlsx:
                              warning("Invalid file! Please use a .csv or .xlsx file")
    )
    # Manipulate the data so that headers is a three column tibble: header 1 = `question_name`, header 2 = `full_text`, and `full_question_text` is the combination of the two:
    headers <- sm_data_headers %>%
        dplyr::mutate(type = c('question_name', 'full_text')) %>%
        tidyr::pivot_longer(!"type") %>%
        tidyr::pivot_wider(names_from = "type", values_from = "value") %>%
        dplyr::select(!"name") %>%
        dplyr::mutate(full_text = dplyr::case_when(.data[["full_text"]] %in% c("Response", "Open-Ended Response") ~ NA_character_, TRUE ~ full_text), # turn "Response" and Open-Ended Response" to NA
                      full_question_text = dplyr::coalesce(.data[["full_text"]], .data[["question_name"]])) # combine two columns into new col, take first non-missing, full_text, then question_name
    return(headers)
}
getHeaders(file_path = "sm_data/fake_sm_post_excel.xlsx")

```


```{r}
# createCodebook() takes one argument, `file_path` = file path of the data from SM to be read in, creates a partial codebook 
#   that can be edited to create useful variable names from SM data.
createCodebook <- function(file_path) {
    codebook <- getHeaders(file_path = file_path) %>% # helper function that returns tibble of 3 cols: question_name, full_text, full_question_text
                dplyr::mutate(variable_name = janitor::make_clean_names(.data[["full_question_text"]]), # make `variable_name` by cleaning names of new col `full_question_text`
                              position = seq_along(.data[["variable_name"]])) # make `position` by cleaning names of new col `full_question_text`
    return(codebook)
}
pre_data_names <- createCodebook("sm_data/fake_sm_pre.csv")
```

```{r}
# renameData() takes two argument, `file_path` = file path of the data from SM to be read in and `codebook` = tibble of codebook from createCodebook() with column named `variable_name`, 
# Reads in the SM data with new variable names taken from the codebook df column named `variable_name`.
readRenameData <- function(file_path, codebook) {
    # Using `getHeaders()`- Condense the two header rows into one row (column named `full_question_text`) and set as a character vector:
    sm_names <- getHeaders(file_path = file_path) %>% # helper function that returns tibble of 3 cols: question_name, full_text, full_question_text
        dplyr::select("full_question_text") %>% # select the combined header
        tibble::deframe() # set as a character vector
    ext <- tools::file_ext(file_path) # get file_path extension
    # Read in the data, using switch with ext from above to determine the function, skipping first 2 lines, and then set the column names using the vector `sm_names`:
    sm_data <- switch(ext,
                      csv = readr::read_csv(file_path, skip = 2, col_names = sm_names, show_col_types = FALSE),
                      xlsx = readxl::read_xlsx(file_path, skip = 2, col_names = sm_names, .name_repair = "unique_quiet"),
                      # Return an error message if file is not .csx or .xlsx:
                      warning("Invalid file! Please use a .csv or .xlsx file")
    )

    # Create a named vector of the columns from `codebook` named `variable_name` and `full_question_text` where `variable_name` is the names and
    # will be the new names in data (tibble::deframe() creates a named vector where `names` is the first col and second col will be the `values`):
    sm_new_names <- {{ codebook }} %>% dplyr::select("variable_name", "full_question_text") %>% tibble::deframe()

    # Use it to rename the vars in `sm_data` so they match (current names of sm_data were `full_question_text`, the use of a named vector ensures the right
    # columns are being renamed):
    sm_data <- sm_data %>% dplyr::rename(!!!sm_new_names)
    sm_data

    return(sm_data)
}

# read in codebook
codebook_pre <- readr::read_csv("sm_data/fake_codebook.csv", show_col_types = FALSE)
# Read in data with new names take from the codebook column named "variable_name":
pre_data <- readRenameData("sm_data/fake_sm_pre.csv", codebook = codebook_pre)
pre_data
```

### How to read in .csv data from SurveyMonkey to create nice variable names:
```{r load in .csv data example}
# Read in the pre fake data data:
# pre_data_names <- readr::read_csv("sm_data/fake_sm_pre.csv", col_names = FALSE, show_col_types = FALSE) %>% slice(1:2) %>%  # read in the first two lines of the .csv file
#     mutate(type = c('question_name', 'full_text')) %>% # name first line 'question_name', and second line 'full_text'
#     tidyr::pivot_longer(!type) |> 
#     tidyr::pivot_wider(names_from = type, values_from = value) |> 
#     select(!name) %>% 
#     mutate(full_text = case_when(full_text == "Response" | full_text == "Open-Ended Response" ~ NA_character_, TRUE ~ full_text), # turn "Response" to NA
#            full_question_text = coalesce(full_text, question_name), # combine two columns into new col, take first non-missing
#            variable_name = janitor::make_clean_names(full_question_text)) # create variable_name col

# createCodebook() takes one argument, `file_path` = file path of the data from SM to be read in, creates a partial codebook 
#   that can be edited to create useful variable names from SM data.
createCodebook <- function(file_path) {
    codebook <- getHeaders(file_path = file_path) %>% # helper function that returns tibble of 3 cols: question_name, full_text, full_question_text
                mutate(variable_name = janitor::make_clean_names(full_question_text), # make `variable_name` by cleaning names of new col `full_question_text`
                       position = seq_along(variable_name)) # make `position` by cleaning names of new col `full_question_text`
    return(codebook)
}
pre_data_names <- createCodebook("sm_data/fake_sm_pre.csv")
# pre_data_names

# Write out codebook, need to go in and edit the column named `variable_name` manually:
# write_csv(pre_data_names, file = "sm_data/fake_codebook.csv")
# variable_name <- c("respondent_id", "collector_id", "start_date", "end_date", "ip_address", "email_address", "first_name", "last_name", "unique_id", "knowledge", 
#                    "research_1", "research_2", "research_3", "research_4", "research_5", "research_6", "research_7", "research_8", 
#                    "ability_1", "ability_2", "ability_3", "ability_4", "ability_5", "ability_6", 
#                    "gender", "ethnicity", "first_gen")

# read in codebook
codebook_pre <- readr::read_csv("sm_data/fake_codebook.csv", show_col_types = FALSE)

# pre_data <- readr::read_csv("sm_data/fake_sm_pre.csv", skip = 2, col_names = FALSE, show_col_types = FALSE) 
# names(pre_data) <- codebook[["variable_name"]]

# sm_names <- readr::read_csv("sm_data/fake_sm_pre.csv", col_names = FALSE, show_col_types = FALSE) %>% slice(1:2) %>%  
#                 mutate(type = c('question_name', 'full_text')) %>% 
#                 tidyr::pivot_longer(!type) |> 
#                 tidyr::pivot_wider(names_from = type, values_from = value) |> 
#                 select(!name) %>% 
#                 mutate(full_text = case_when(full_text == "Response" | full_text == "Open-Ended Response" ~ NA_character_, TRUE ~ full_text), # turn "Response" to NA
#                        full_question_text = coalesce(full_text, question_name)) %>%  # combine two columns into new col, take first non-missing, full_text, then question_name
#                 select(full_question_text) %>% 
#                 tibble::deframe()
# 
# sm_data_new <- readr::read_csv("sm_data/fake_sm_pre.csv", skip = 2, col_names = FALSE, show_col_types = FALSE) 
# names(sm_data_new) <- sm_names
# # Creat a named vector of the columns 
# sm_new_names <- codebook_pre %>% select(variable_name, full_question_text) %>% tibble::deframe()
# # use it to rename the vars:
# sm_data_new <- sm_data_new %>% rename(!!!sm_new_names)
# sm_data_new
# renameData() takes two argument, `file_path` = file path of the data from SM to be read in and `codebook` = tibble of codebook from createCodebook() with column named `variable_name`, 
# Reads in the SM data with new variable names taken from the codebook df column named `variable_name`.
readRenameData <- function(file_path, codebook) {
    # Using `getHeaders()`- Condense the two header rows into one row (column named `full_question_text`) and set as a character vector:
    sm_names <- getHeaders(file_path = file_path) %>% # helper function that returns tibble of 3 cols: question_name, full_text, full_question_text
                dplyr::select(full_question_text) %>% # select the combined header
                tibble::deframe() # set as a character vector
    ext <- tools::file_ext(file_path) # get file_path extension
    # Read in the data, using switch with ext from above to determine the function, skipping first 2 lines, and then set the column names using the vector `sm_names`:
    sm_data <- switch(ext,
                      csv = readr::read_csv(file_path, skip = 2, col_names = sm_names, show_col_types = FALSE),
                      xlsx = readxl::read_xlsx(file_path, skip = 2, col_names = sm_names, .name_repair = "unique_quiet"),
                      # Return an error message if file is not .csx or .xlsx:
                      warning("Invalid file! Please use a .csv or .xlsx file")
                      )
    
    # Create a named vector of the columns from `codebook` named `variable_name` and `full_question_text` where `variable_name` is the names and 
    # will be the new names in data (tibble::deframe() creates a named vector where `names` is the first col and second col will be the `values`):
    sm_new_names <- {{ codebook }} %>% dplyr::select(variable_name, full_question_text) %>% tibble::deframe()
    
    # Use it to rename the vars in `sm_data` so they match (current names of sm_data were `full_question_text`, the use of a named vector ensures the right 
    # columns are being renamed):
    sm_data <- sm_data %>% dplyr::rename(!!!sm_new_names)
    sm_data
    
    return(sm_data)
}

pre_data <- readRenameData("sm_data/fake_sm_pre.csv", codebook = codebook_pre)
pre_data
# Read in the post fake data:
# post_data <- readr::read_csv("sm_data/fake_sm_post.csv")

```


    
### Test on fake post data:
```{r}
# TODO: turn this into a vignette for reading in data from SurveyMonkey:

# File path for post data:
post_data_fp <- "sm_data/fake_sm_post.csv"
# 1. Create the codebook:
codebook_post <- createCodebook(post_data_fp)

# One way to change the `variable_name` column without position numbers: ----
# # Create names as vectors:
# research_names <- purrr::map_chr(1:8, \(x) paste0("research_",x))
# ability_names <- purrr::map_chr(1:6, \(x) paste0("ability_",x))
# 
# # Create old Names as vectors:
# research_vals <- c("research_relevant_background_literature", "identify_a_scientific_problem", "develop_testable_and_realistic_research_questions", "develop_a_falsifiable_hypothesis", 
#                    "conduct_quantitative_data_analysis", "design_an_experiment_create_a_research_design", "interpret_findings_and_making_recommendations", "scientific_or_technical_writing")
# ability_vals <- c("judge_the_value_of_new_information_or_evidence_presented_to_me", "approach_complex_issues_in_a_variety_of_ways", "weigh_both_sides_of_an_argument", 
#                   "identify_analogies_between_theories", "eliminate_extraneous_variables_when_designing_experiments", "rephrase_the_arguments_of_others_in_my_own_words")
# # Use replace and case_when to change all variable names, inside replace, select the old names using the _vals vectors and replace with the _names vectors:
# codebook_post <- codebook_post %>% mutate(variable_name = replace(variable_name, variable_name %in% research_vals, research_names),
#                                           variable_name = replace(variable_name, variable_name %in% ability_vals, ability_names),
#                                          variable_name = case_match(variable_name,
#                                                                     'custom_data_1' ~ "unique_id",
#                                                                     'to_what_extent_are_you_knowledgeable_in_conducting_research_in_your_field_of_study' ~ "knowledge",
#                                                                     'with_which_gender_do_you_most_closely_identify' ~ "gender",
#                                                                     'which_race_ethnicity_best_describes_you_please_choose_only_one' ~ "ethnicity",
#                                                                     'are_you_a_first_generation_college_student' ~ "first_gen",
#                                                                      .default = variable_name) # returns default value of the original variable 11:18
#                                           )

# Step 2. Edit the codebook: --------
# Set up variables with shared root names:
# Another way to change the `variable_name` column with position numbers:
# 8 items that are matrix-style likert scales- turned into a scale called `research`- here is how to easily name them all at once:
# Columns 11 to 18 belong to the "research" matrix question
research_items <- codebook_post[["variable_name"]][11:18]

# Create a new named vector of names for these columns
research_names <- paste0("research_", seq_along(research_items)) %>% purrr::set_names(., research_items)

# 6 items that are matrix-style likert scales- turned into a scale called `ability`- here is how to easily name them all at once:
# Columns 19 to 24 belong to the "ability" matrix question: selecting by row position in column named `variable_name`:
ability_items <- codebook_post[["variable_name"]][19:24]
# # this works too:
# ability_items  <- codebook_post[["variable_name"]][match("judge_the_value_of_new_information_or_evidence_presented_to_me", codebook_post[["variable_name"]]):match("rephrase_the_arguments_of_others_in_my_own_words", codebook_post[["variable_name"]])]
# # and this:
# codebook_post %>% select(variable_name) %>%  
#     dplyr::slice(match("judge_the_value_of_new_information_or_evidence_presented_to_me", variable_name):match("rephrase_the_arguments_of_others_in_my_own_words", variable_name)) %>% 
#     tibble::deframe()

# Create a new vector of names for these columns
ability_names <- paste0("ability_", seq_along(ability_items)) %>% purrr::set_names(., ability_items)

# Edit the `variable_names` column
# Use dplyr::mutate() and dplyr::case_match() to change the column `variable_name`:
codebook_post <- codebook_post %>% dplyr::mutate(
    variable_name = dplyr::case_match(
        variable_name, # column to match
        'custom_data_1' ~ "unique_id", # changes 'custom_data_1' to "unique_id"
        'to_what_extent_are_you_knowledgeable_in_conducting_research_in_your_field_of_study' ~ "knowledge",
        'with_which_gender_do_you_most_closely_identify' ~ "gender",
        'which_race_ethnicity_best_describes_you_please_choose_only_one' ~ "ethnicity",
        'are_you_a_first_generation_college_student' ~ "first_gen",
        names(research_names) ~ research_names[variable_name], # takes the above named vector and when the name matches, applies new value in that position as replacement.
        names(ability_names) ~ ability_names[variable_name],   # Same for `ability_names`
        .default = variable_name # returns default value from original `variable_name` if not changed.
        )
    )

# Write out the edited codebook, be sure to double check questions match new names before writing out:
readr::write_csv(codebook_post, file = "sm_data/fake_codebook_post.csv")

# Read in the codebook: 
codebook_post <- readr::read_csv("sm_data/fake_codebook_post.csv", show_col_types = FALSE)
# 3. Read in the data and rename the vars using readRenameData(), passing the file path and the edited codebook: -----
post_data <- readRenameData(post_data_fp, codebook = codebook_post)
post_data
```

```{r}
# chatGPT suggestion:
# Load the readr package
# library(readr)
# library(dplyr)

# Read the first two lines as header
header_lines <- read_lines("sm_data/fake_sm_post.csv", n_max = 2)

# Split the lines by comma to create individual headers
header1 <- unlist(strsplit(header_lines[1], ","))
header2 <- unlist(strsplit(header_lines[2], ","))

# Create a new header by combining the two headers
new_header <- paste(header1, header2, sep = " - ")

# Read the rest of the data starting from the third line
data <- read_csv("path/to/your/survey.csv", skip = 2, col_names = new_header)

# Display the first few rows of the data with long column names
print(head(data))
print(colnames(data))  # Print original column names

# Create a named vector for meaningful short names
meaningful_names <- c(
  "Survey_Date" = "Start Date - Date the survey was taken",
  "Respondent_ID" = "Response ID - Unique ID for each response",
  "Age" = "Q1 - Age of the respondent",
  "Satisfaction_Level" = "Q2 - Satisfaction with the product",
  "Recommend_Friend" = "Q3 - Likelihood to recommend to a friend"
  # Add other mappings as needed
)

# Rename the columns using dplyr
data <- data %>% rename(!!!meaningful_names)

# Display the first few rows of the data with new column names
print(head(data))
print(colnames(data))  # Print new column names

# Assume that columns 5 to 10 belong to the "ability" matrix question
ability_columns <- colnames(data)[5:10]

# Create a new vector of names for these columns
new_ability_names <- paste0("ability_", seq_along(ability_columns))

# Create a named vector to map old names to new names
names_mapping <- setNames(new_ability_names, ability_columns)

# Rename the columns using dplyr
data <- data %>% rename(!!!names_mapping)

# Display the first few rows of the data with new column names
print(head(data))
print(colnames(data))  # Print new column names


```


```{r}
post_data %>% names()
```

### Create fake data based on SurveyMonkey data from this file:

```{r fake sm data demos}
library(charlatan) # for creating fake data
# setup the providers for charlatan
ip <- InternetProvider_en_US$new()
lp <- LoremProvider_en_US$new()
np <- NumericsProvider$new()
person <- PersonProvider_en_US$new()

# Total N of 100 clients:
n <- 100

# SurveyMonkey respondent_id, numeric vector
respondent_id <- as.numeric(114628000001:114628000100)

# IP address and emails:
email_address <- sapply(1:n, function(x) ip$email())
ip_address  <- sapply(1:n, function(x) ip$ipv4())

# Generate Unique ID, generate 100 with starting number of 24290001:
unique_id <- as.numeric(24290001:24290100)

# Names from the `charlatan` package, create 300 male and 300 female names and last names as vectors:
female_names <- sapply(1:n , function(x) person$first_name_female())
last_names_female <- sapply(1:n , function(x) person$last_name_female())
male_names <- sapply(1:n , function(x) person$first_name_male())
last_names_male <- sapply(1:n , function(x) person$last_name_male())

# Add unique_id to tibble and generate gender, first and last names, age, ethnicity, zip code, session_location using sample of size 100:
data_unique <- tibble(
    respondent_id = respondent_id, # from above
    collector_id = as.numeric(431822954), # same number- assuming that is how SM does it
    start_date = sample(seq(as.Date("2024-06-01"), as.Date("2024-06-25"), by = "day"), size = n, replace = TRUE),
    end_date = start_date + 1,
    ip_address = ip_address, # from above
    email_address = email_address, # from above
    gender = sample(c("Female","Male","Non-binary", "Do not wish to specify"), size = n, replace = TRUE, prob = c(0.52, 0.44, 0.02, 0.02)),
    first_name = if_else(gender == "Female", sample(female_names), sample(male_names)), # sample from female names vector if gender is female, otherwise use male name vector.
    last_name = if_else(gender == "Female", sample(last_names_female), sample(last_names_male)), # sample from female last names vector if gender is female, otherwise use  male last name vector.
    unique_id = unique_id, # from above
    ethnicity = sample(c("White (Non-Hispanic/Latino)", "Asian", "Black",  "Hispanic or Latino", "American Indian or Alaskan Native",
                         "Native Hawaiian or other Pacific Islander", "Do not wish to specify"), size = n, replace = TRUE, prob = c(0.32, 0.21, 0.15, 0.20, 0.05, 0.06, 0.01)),
    first_gen = sample(c("Yes", "No", "I'm not sure"), size = n, replace = TRUE, prob = c(0.55, 0.44, 0.01))
) %>% select(respondent_id, collector_id, start_date, end_date, ip_address, email_address, first_name, last_name, unique_id, gender, ethnicity, first_gen) # set correct order
data_unique
# readr::read_csv("sm_data/fake_sm_pre.csv", show_col_types = FALSE)

# Write out data tibble with sm data and demos to `data-raw` folder:
# readr::write_csv(data_unique, "../data-raw/data_sm_demo.csv")

```
