---
title: "Introduction to bre"
output: rmarkdown::html_vignette
description: >
  Start here if this is your first time using bre.
vignette: >
  %\VignetteIndexEntry{Introduction to bre}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup,  echo = FALSE, message = FALSE, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE, 
  message = FALSE, 
  out.width = "100%",
  tibble.print_min = 5L, 
  tibble.print_max = 5L
)
options(scipen = 999, digits = 4) # Prevents sci notation and sets the output of decimals to 4 (0.0000)
library(bre) # load Blackstone R package
set.seed(424629) # set reproducible seed
```


Blackstone Research and Evaluation uses the `R` programming language as its main tool for data analysis and visualization.
The main goal of `bre` is to make the process of coding in `R` as efficient as possible for everyone at Blackstone Research and Evaluation.

In order to reach this goal, `bre` leverages established `R` packages and the [tidyverse](https://www.tidyverse.org/) family of `R` packages in particular. 
The vignettes provided with `bre` will go into greater detail as to how to use `bre` alongside these other packages.
This document introduces you to `bre` and how it fits into the basic workflow of data analysis and visualization at Blackstone Research and Evaluation.

## Overview of Workflow

* Import and clean data from survey provider.

* Simple data analysis and statistical inference.

* Data visualization and output for report writing.




